### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by ajanieniolasolomon** [transistorsoft/flutter_background_geolocation_firebase#12]
**Your Environment**
* Plugin version:: 1.2.1
* Platform: iOS 
* OS version:9
* Device manufacturer / model:Iphone XR
* Flutter info (`flutter info`, `flutter doctor`):
[✓] Flutter (Channel dev, v1.13.9, on Mac OS X 10.15.3 19D76, locale en-GB)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
[✓] Android Studio (version 3.4)
[✓] IntelliJ IDEA Community Edition (version 2019.3)
[✓] VS Code (version 1.43.0)
[✓] Connected device (1 available)
* Plugin config

  background_geolocation_firebase:
    git:
      url: https://github.com/transistorsoft/flutter_background_geolocation_firebase

**To Reproduce**
1. 
2.
3.
4.

**Debug logs**
- ios XCode logs, 
- Android: `$ adb logcat`

**Additional context**

1 error generated.
    /Users/ajanieniola/Downloads/flutter/.pub-cache/hosted/pub.dartlang.org/background_fetch-0.5.4/ios/Classes/BackgroundFetchPlugin.m:2:9: fatal error: could not build module 'TSBackgroundFetch'
    #import <TSBackgroundFetch/TSBackgroundFetch.h>
     ~~~~~~~^

**Comment by christocracy** [comment]
Your error is with `BackgroundFetch`, not this firebase adapter.  Have you installed `flutter_background_geolocation`?

```
/Users/ajanieniola/Downloads/flutter/.pub-cache/hosted/pub.dartlang.org/background_fetch-0.5.4/ios/Classes/BackgroundFetchPlugin.m:2:9: fatal error: could not build module 'TSBackgroundFetch'
#import <TSBackgroundFetch/TSBackgroundFetch.h>
```

**Comment by christocracy** [comment]
Also, please post a more informative subject than "BUG".  This is not even a bug, it's a Setup issue.

**Comment by ajanieniolasolomon** [comment]
It affects all the plugging

**Comment by christocracy** [comment]
```
$ cd ios
$ pod install
```
Show me your `pubspec.yaml`

**Comment by ajanieniolasolomon** [comment]
How can i effective test geofencing. Try testing it in background with
local notifications not working.

**Comment by christocracy** [comment]
This issue, which you poorly titled “*BUG*”, which has nothing to do with “geofencing”, is closed.
