### ISSUE TITLE
How can I add extra data to the default Location Data Schema

### ISSUE THREAD

**Issue by iDeliverApps** [transistorsoft/flutter_background_geolocation_firebase#13]
In your Firebase Functions section on your example, you show the default schema with additional parameters param1 and param2 

{
  "location":{},
  "param1": "param 1",
  "param2": "param 2"
}

How do I override the default schema with my additional parameters?

**Comment by christocracy** [comment]
See API docs [`Config.extras`](https://pub.dev/documentation/flutter_background_geolocation/latest/flt_background_geolocation/Config/extras.html)

**Comment by christocracy** [comment]
And `Config.params`

**Comment by iDeliverApps** [comment]
Gotit. Thanks very much.
