### ISSUE TITLE
How to customize the data sent to Firebase?

### ISSUE THREAD

**Issue by ViniciusDiasSilva** [transistorsoft/flutter_background_geolocation_firebase#19]
I would like to use geopoint and timestamp fields for example...

**Comment by christocracy** [comment]
What is a "geopoint"?

I don't understand at all what you're asking.

**Comment by ViniciusDiasSilva** [comment]
Is a type data field 
![Screen Shot 2021-04-09 at 17 31 47](https://user-images.githubusercontent.com/33465742/114237473-86f0d000-9959-11eb-84ef-42df03dba0c2.png)

**Comment by christocracy** [comment]
See the readme about using Firebase functions to transform the data however you wish, after it arrives from the plugin.

Functions that don't involve network have a negligible cost.

**Comment by ViniciusDiasSilva** [comment]
This will generate a consumption of unnecessary resources, both in functions and in the firebase itself, that is, it is not commercially viable and scalable.

**Comment by christocracy** [comment]
> that is, it is not commercially viable and scalable.

This is absolutely false.  Why do you think [Cloud Functions](https://firebase.google.com/docs/functions/) exist?  

it's [$7.20/month for 10M invocations](https://cloud.google.com/functions/pricing).

It's also your only option.  The schema of posted records is not going to change.
