### ISSUE TITLE
Could not find com.transistorsoft:tsfirebaseproxy

### ISSUE THREAD

**Issue by FabrizioBilleciUNICT** [transistorsoft/flutter_background_geolocation_firebase#26]
Hi. I'm using your plugin for the Background Geolocation for Flutter, but I have a problem when I try to start the application:
Could not find com.transistorsoft:tsfirebaseproxy

**Comment by christocracy** [comment]
You didn’t follow the required Setup Instructions linked in the readme.

**Comment by DevMayur** [comment]
Could not find any matches for com.transistorsoft:tsfirebaseproxy:+ as no versions of com.transistorsoft:tsfirebaseproxy are available.

**Comment by DevMayur** [comment]
Added         maven {
            url "${project(':background_geolocation_firebase').projectDir}/libs"
        }

in allprojects android build.gradle.

The above line should fix this issue.

@transistorsoft-pkg Please add this instruction in the readme in flutter pub.

**Comment by christocracy** [comment]
Is there something missing in the [Setup Docs](https://github.com/transistorsoft/flutter_background_geolocation_firebase/blob/master/help/INSTALL-ANDROID.md)?

**Comment by DevMayur** [comment]
I am referring to the readme on the pub.dev There is no mention of this.

**Comment by christocracy** [comment]
If you’re talking about the “Installing” tab at pub.dev, that’s auto-generated.

The readme at pub.dev is taken exactly from the GitHub repo, which contains a link to *Setup Guides*.  You need to read the readme to install this plugin.
