### ISSUE TITLE
[FirebaseFirestore][I-FST000001] Write at locations/FebXQEgcwFoZw0SmS68I failed: Missing or insufficient permissions.

### ISSUE THREAD

**Issue by grecky-goo** [transistorsoft/flutter_background_geolocation_firebase#31]
**Your Environment**
* Plugin version:
* Platform: iOS
* OS version: 17.5.1
* Device manufacturer / model: Iphone 14 pro
* Flutter info (`flutter info`, `flutter doctor`):
*Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.22.2, on macOS 14.4 23E214 darwin-x64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.3)
[✓] VS Code (version 1.90.2)
[✓] Connected device (3 available)
    ! Error: Browsing on the local area network for iPhone. Ensure the device is unlocked and attached with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
[✓] Network resources
* Plugin config
BackgroundGeolocationFirebase.configure(BackgroundGeolocationFirebaseConfig(
      locationsCollection: "locations",
      geofencesCollection: "geofences",
      updateSingleDocument: false));
  bg.BackgroundGeolocation.ready(bg.Config(
          debug: true,
          distanceFilter: 50,
          logLevel: bg.Config.LOG_LEVEL_VERBOSE,
          stopTimeout: 1,
          stopOnTerminate: false,
          startOnBoot: true))
      .then((bg.State state) {
    print(
        '[locationServiceIntilize] ****** Starting Service.  enabled:$state.enabled ');
    appState.enabled = state.enabled;
    bg.BackgroundGeolocation.start();
  });

**To Reproduce**
I am integrating the plugin into a Flutterflow application.  I am receiving insufficient permissions error even though I have the database rules open.  I am using Flutterflow to login, but I can't figure out how to pass the credentials for the plugin to write to the database.  Start the application, login, then start the background location updates.  The location is returned, but the database write fails.

**Debug logs**

[TSBackgroundFetch load]: (
)
[TSBGAppRefreshSubscriber load]: {
    TSLocationManager = "<TSBGAppRefreshSubscriber identifier=TSLocationManager, executed=0, enabled=1>";
}
10.25.0 - [FirebaseCore][I-COR000005] No app has been configured yet.
ℹ️-[TSDBLogger db_delete] maxAge: 259200
ℹ️-[TSLocationManager init] 
╔═════════════════════════════════════════════
║ TSLocationManager (build 388)
╠══════════════════════════════════════════════
{
    activityRecognitionInterval = 10000;
    activityType = 1;
    authorization =     {
    };
    autoSync = 1;
    autoSyncThreshold = 0;
    batchSync = 0;
    debug = 1;
    desiredAccuracy = "-1";
    desiredOdometerAccuracy = 100;
    didDeviceReboot = 0;
    didLaunchInBackground = 0;
    didRequestUpgradeLocationAuthorization = 1;
    disableAutoSyncOnCellular = 0;
    disableElasticity = 0;
    disableLocationAuthorizationAlert = 0;
    disableMotionActivityUpdates = 0;
    disableStopDetection = 0;
    distanceFilter = 50;
    elasticityMultiplier = 1;
    enableTimestampMeta = 0;
    enabled = 1;
    extras =     {
    };
    geofenceInitialTriggerEntry = 1;
    geofenceProximityRadius = 2000;
    geofenceTemplate = "";
    headers =     {
    };
    heartbeatInterval = 60;
    httpRootProperty = location;
    httpTimeout = 60000;
    iOSHasWarnedLocationServicesOff = 1;
    isFirstBoot = 0;
    isMoving = 0;
    lastLocationAuthorizationStatus = 3;
    locationAuthorizationAlert =     {
        cancelButton = Cancel;
        instructions = "To use background location, you must enable '{locationAuthorizationRequest}' in the Location Services settings";
        settingsButton = Settings;
        titleWhenNotEnabled = "Background location is not enabled";
        titleWhenOff = "Location services are off";
    };
    locationAuthorizationRequest = Always;
    locationTemplate = "";
    locationTimeout = 60;
    locationsOrderDirection = ASC;
    logLevel = 5;
    logMaxDays = 3;
    maxBatchSize = "-1";
    maxDaysToPersist = 1;
    maxRecordsToPersist = "-1";
    method = POST;
    minimumActivityRecognitionConfidence = 70;
    odometer = "23.88443965316369";
    params =     {
    };
    pausesLocationUpdatesAutomatically = 1;
    persistMode = 2;
    preventSuspend = 0;
    schedule =     (
    );
    schedulerEnabled = 0;
    showsBackgroundLocationIndicator = 1;
    startOnBoot = 1;
    stationaryRadius = 25;
    stopAfterElapsedMinutes = "-1";
    stopDetectionDelay = 0;
    stopOnStationary = 0;
    stopOnTerminate = 0;
    stopTimeout = 1;
    trackingMode = 1;
    url = "";
    useSignificantChangesOnly = 0;
}
ℹ️-[GeofenceDAO init] CREATE TABLE IF NOT EXISTS geofences (id INTEGER PRIMARY KEY AUTOINCREMENT, identifier TEXT NOT NULL UNIQUE, latitude DOUBLE NOT NULL, sin_latitude DOUBLE NOT NULL, cos_latitude DOUBLE NOT NULL, longitude DOUBLE NOT NULL, sin_longitude DOUBLE NOT NULL, cos_longitude DOUBLE NOT NULL, radius DOUBLE NOT NULL, notifyOnEntry BOOLEAN NOT NULL DEFAULT 0, notifyOnExit BOOLEAN NOT NULL DEFAULT 0, notifyOnDwell BOOLEAN NOT NULL DEFAULT 0, loiteringDelay DOUBLE NOT NULL DEFAULT 0, extras TEXT, vertices TEXT)
ℹ️-[GeofenceDAO init] CREATE index IF NOT EXISTS identifier ON geofences (identifier);CREATE index IF NOT EXISTS latitude ON geofences (latitude);CREATE index IF NOT EXISTS longitude ON geofences (longitude);CREATE index IF NOT EXISTS sin_latitude ON geofences (sin_latitude);CREATE index IF NOT EXISTS cos_latitude ON geofences (cos_latitude);CREATE index IF NOT EXISTS sin_longitude ON geofences (sin_longitude);CREATE index IF NOT EXISTS cos_longitude ON geofences (cos_longitude);
🔵-[TSLocationManager locationManager:didChangeAuthorizationStatus:] status 3
🔵-[LocationManager locationManager:didChangeAuthorizationStatus:] 3
🔵-[PolygonGeofencingService locationManager:didChangeAuthorizationStatus:] 3
🔵-[LocationManager locationManager:didChangeAuthorizationStatus:] 3
🔵-[BackgroundTaskManager locationManager:didChangeAuthorizationStatus:] 3
🔵-[LocationManager locationManager:didChangeAuthorizationStatus:] 3
ℹ️+[LocationAuthorization run:onCancel:] status: 3
flutter: The Dart VM service is listening on http://127.0.0.1:56007/NVImy-tOop8=/
10.25.0 - [FirebaseAnalytics][I-ACS023007] Analytics v.10.25.0 started
10.25.0 - [FirebaseAnalytics][I-ACS023008] To enable debug logging set the following application argument: -FIRAnalyticsDebugEnabled (see http://goo.gl/RfcP7r)
10.25.0 - [FirebaseAnalytics][I-ACS044002] The AdSupport Framework is not currently linked. Some features will not function properly. Learn more at http://goo.gl/9vSsPb
10.25.0 - [FirebaseAnalytics][I-ACS800023] No pending snapshot to activate. SDK name: app_measurement
10.25.0 - [FirebaseAnalytics][I-ACS023012] Analytics collection enabled
10.25.0 - [FirebaseAnalytics][I-ACS023220] Analytics screen reporting is enabled. Call Analytics.logEvent(AnalyticsEventScreenView, parameters: [...]) to log a screen view event. To disable automatic screen reporting, set the flag FirebaseAutomaticScreenReportingEnabled to NO (boolean) in the Info.plist
-[RTIInputSystemClient remoteTextInputSessionWithID:performInputOperation:]  perform input operation requires a valid sessionID. inputModality = Keyboard, inputOperation = <null selector>, customInfoType = UIEmojiSearchOperations
-[RTIInputSystemClient remoteTextInputSessionWithID:performInputOperation:]  perform input operation requires a valid sessionID. inputModality = Keyboard, inputOperation = <null selector>, customInfoType = UIEmojiSearchOperations
-[RTIInputSystemClient remoteTextInputSessionWithID:performInputOperation:]  perform input operation requires a valid sessionID. inputModality = Keyboard, inputOperation = <null selector>, customInfoType = UIEmojiSearchOperations
flutter: [locationServiceInitialize) ********************************
ℹ️-[TSLocationManager on:success:failure:] location
ℹ️-[TSConfig persist]
ℹ️-[TSConfig persist]
🔵-[TSLocationManager ready]
ℹ️-[TSLocationManager doStart:] trackingMode: 1
ℹ️-[TSLocationManager loadLastOdometerLocation] <+37.23097711,-121.88046926> +/- -1.00m (speed -1.00 mps / course -1.00) @ 8/28/24, 9:03:15 AM Pacific Daylight Time
🎾-[TSGeofenceManager start]
🎾-[SOMotionDetector startDetection]
🔵-[TSLocationManager setPace:] 0
🎾-[TSLocationManager startUpdatingLocation] Location-services: ON
ℹ️-[PolygonGeofencingService setLocation:] Already updating location <IGNORED>
flutter: [location] [Location {uuid: B4842DF2-2640-4261-B4A7-F5A55E549F94, odometer: 23.9, sample: true, extras: {}, age: 4486, timestamp: 2024-08-28T16:03:10.810Z, battery: {level: -1.0, is_charging: false}, coords: {speed_accuracy: -1.0, speed: -1.0, longitude: -121.88046926200774, ellipsoidal_altitude: 38.99, floor: 2146959360, heading_accuracy: -1.0, latitude: 37.23095703125, accuracy: 5.0, altitude_accuracy: 18.44, altitude: 71.61, heading: -1.0}, is_moving: false, activity: {type: unknown, confidence: 100}}]
flutter: [locationServiceIntilize] ****** Starting Service.  enabled:[State enabled: true, isMoving: false, trackingMode: 1, desiredAccuracy: -1, distanceFilter: 50.0, odometer: 23.88443965316369, schedulerEnabled: false, foregroundService: null].enabled

╔═══════════════════════════════════════════════════════════
║ -[TSHttpService flush:] 
╚═══════════════════════════════════════════════════════════

╔═══════════════════════════════════════════════════════════
║ -[TSHttpService finish:error:] Success: 0
╚═══════════════════════════════════════════════════════════
ℹ️+[LocationAuthorization run:onCancel:] status: 3
🎾-[TSLocationManager startMonitoringBackgroundFetch] BackgroundFetch: ON
ℹ️-[TSLocationManager startMonitoringBackgroundFetch]_block_invoke Configured BackgroundFetch
⚠️-[TSLocationManager start] Already started (ignored)
✅-[SOMotionDetector startDetection]_block_invoke Enabled M7 MotionActivity updates

📍<+37.23097711,-121.88046926> +/- 5.00m (speed -1.00 mps / course -1.00) @ 8/28/24, 9:03:01 AM Pacific Daylight Time
flutter: [location] [Location {uuid: A0C7D149-467B-475A-8AD7-2F54F96D5CAE, odometer: 23.9, extras: {}, age: 4522, timestamp: 2024-08-28T16:03:10.810Z, battery: {level: 1.0, is_charging: true}, event: motionchange, coords: {speed_accuracy: -1.0, speed: -1.0, longitude: -121.88046926200774, ellipsoidal_altitude: 38.99, floor: null, heading_accuracy: -1.0, latitude: 37.230977109625705, accuracy: 5.0, altitude_accuracy: 18.44, altitude: 71.61, heading: -1.0}, is_moving: false, activity: {type: unknown, confidence: 100}}]

╔═══════════════════════════════════════════════════════════
║ -[TSLocationManager locationManager:didUpdateLocations:] Enabled: 1 | isMoving: 0 | df: -1.0m | age: 13512 ms
╚═══════════════════════════════════════════════════════════
ℹ️-[TSLocationManager locationManager:didUpdateLocations:] Received stale motionchange location.  Retrying...

📍<+37.23097711,-121.88046926> +/- 5.00m (speed -1.00 mps / course -1.00) @ 8/28/24, 9:03:10 AM Pacific Daylight Time

╔═══════════════════════════════════════════════════════════
║ -[TSLocationManager locationManager:didUpdateLocations:] Enabled: 1 | isMoving: 0 | df: -1.0m | age: 4521 ms
╚═══════════════════════════════════════════════════════════
✅-[TSLocationManager locationManager:didUpdateLocations:] Acquired motionchange position: <+37.23097711,-121.88046926> +/- 5.00m (speed -1.00 mps / course -1.00) @ 8/28/24, 9:03:10 AM Pacific Daylight Time
🔵-[TSLocationManager startMonitoringStationaryRegion:radius:] Radius: 200
🔴-[TSLocationManager stopUpdatingLocation]
🔵-[TSLocationManager calculateMedianLocationAccuracy:] Median location accuracy: 5.0
ℹ️-[PolygonGeofencingService setLocation:] Already updating location <IGNORED>
🎾-[TSLocationManager startMonitoringSignificantLocationChanges]
Error adding document: Error Domain=FIRFirestoreErrorDomain Code=7 "Missing or insufficient permissions." UserInfo={NSLocalizedDescription=Missing or insufficient permissions.}
10.25.0 - [FirebaseFirestore][I-FST000001] WriteStream (hˌ\^D\^A
10.25.0 - [FirebaseFirestore][I-FST000001] Write at locations/FebXQEgcwFoZw0SmS68I failed: Missing or insufficient permissions.
Client authentication failed; app will be blocked.
Connection terminated.

**Additional context**

**Comment by christocracy** [comment]
You’re responsible for authenticating with your Firebase app.

https://stackoverflow.com/questions/46590155/firestore-permission-denied-missing-or-insufficient-permissions
