### ISSUE TITLE
[BUG] Namespace not specified. Specify a namespace in the module's build file

### ISSUE THREAD

**Issue by aweiand** [transistorsoft/flutter_background_geolocation_firebase#33]
**Your Environment**
* Plugin version: 
1.0.1
* Platform: 
Android
* OS version:
 34
* Device manufacturer / model: 
emulator
* Flutter info (`flutter info`, `flutter doctor`):
Doctor summary (to see all details, run flutter doctor -v):
[!] Flutter (Channel stable, 3.24.3, on Ubuntu 22.04.5 LTS 6.8.0-45-generic, locale pt_BR.UTF-8)
    ! Warning: `dart` on your path resolves to /usr/lib/dart/bin/dart, which is not inside your ...
[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 2024.1)
[✓] VS Code (version 1.94.2)
[✓] Connected device (3 available)
[✓] Network resources

! Doctor found issues in 1 category.

* Plugin config
Only the basic

**To Reproduce**
1. flutter build apk --debug

**Debug logs**
<details>
FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* What went wrong:
A problem occurred configuring project ':background_geolocation_firebase'.
> Could not create an instance of type com.android.build.api.variant.impl.LibraryVariantBuilderImpl.
   > Namespace not specified. Specify a namespace in the module's build file. See https://d.android.com/r/tools/upgrade-assistant/set-namespace for information about setting the namespace.

     If you've specified the package attribute in the source AndroidManifest.xml, you can use the AGP Upgrade Assistant to migrate to the namespace value in the build file. Refer to https://d.android.com/r/tools/upgrade-assistant/agp-upgrade-assistant for general information about using the AGP Upgrade Assistant.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
Failed to query the value of property 'buildFlowServiceProperty'.
> Could not isolate value org.jetbrains.kotlin.gradle.plugin.statistics.BuildFlowService$Parameters_Decorated@52b1fad9 of type BuildFlowService.Parameters
   > A problem occurred configuring project ':background_geolocation_firebase'.
      > Could not create an instance of type com.android.build.api.variant.impl.LibraryVariantBuilderImpl.
         > Namespace not specified. Specify a namespace in the module's build file. See https://d.android.com/r/tools/upgrade-assistant/set-namespace for information about setting the namespace.

           If you've specified the package attribute in the source AndroidManifest.xml, you can use the AGP Upgrade Assistant to migrate to the namespace value in the build file. Refer to https://d.android.com/r/tools/upgrade-assistant/agp-upgrade-assistant for general information about using the AGP Upgrade Assistant.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.
==============================================================================

BUILD FAILED in 2s
Running Gradle task 'assembleDebug'...                           2.279ms
Gradle task assembleDebug failed with exit code 1
</details>

**Additional context**
The bug occours when we are trying to compile the app, with gradle-8.10.2

**Comment by christocracy** [comment]
Ok, the Android gradle Config needed some updating. I’ve got all that figured out.  I’ll have a look at iOS now.  Should have a release ready on Monday or Tuesday.

**Comment by christocracy** [comment]
Ok, I got iOS updated quicker than I expected.  Please give it a test by installing from the git branch `update-dependencies`:

```yaml
dependencies:
  background_geolocation_firebase:
    git:
      url: https://github.com/transistorsoft/flutter_background_geolocation_firebase
      ref: update-dependencies
```

Also, the [*Setup Instructions*](https://github.com/transistorsoft/flutter_background_geolocation_firebase/tree/update-dependencies/help) for both [iOS](https://github.com/transistorsoft/flutter_background_geolocation_firebase/blob/update-dependencies/help/INSTALL-IOS.md) and [Android](https://github.com/transistorsoft/flutter_background_geolocation_firebase/blob/update-dependencies/help/INSTALL-ANDROID.md) have been updated.

**Comment by christocracy** [comment]
Have you tested this yet?

**Comment by aweiand** [comment]
> Have you tested this yet?

Sorry, I didn't test yet. Maybe tomorrow we can do a test, thanks for the quickly response!

**Comment by aweiand** [comment]
I'm testing now and working like a charm! Thanks again!

**Comment by christocracy** [comment]
Great, thanks.  This will be merged tomorrow and released.

**Comment by christocracy** [comment]
`v1.1.0` is released to `pub.dev`
