### ISSUE TITLE
[BUG]  background_geolocation_firebase any which doesn't exist 

### ISSUE THREAD

**Issue by joe69** [transistorsoft/flutter_background_geolocation_firebase#8]
**Your Environment**
* Plugin version: 
0.1.0
* Platform: iOS or Android:
Both
* OS version:
MacOs
* Device manufacturer / model:
* Flutter info (`flutter info`, `flutter doctor`):
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.7.8+hotfix.3, on Mac OS X 10.14 18A391, locale de-AT)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 10.1)
[✓] iOS tools - develop for iOS devices
[!] Android Studio (version 3.0)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] IntelliJ IDEA Ultimate Edition (version 2017.3.4)
[✓] VS Code (version 1.36.1)
[✓] Connected device (1 available)

* Plugin config

**To Reproduce**
1. insert pubspec.yaml 

  flutter_background_geolocation: ^1.2.0
  background_geolocation_firebase: ^0.1.0

flutter packages get
Because stella_di_mare depends on background_geolocation_firebase any which doesn't exist (could not find package background_geolocation_firebase at https://pub.dartlang.org), version solving failed.

**Comment by christocracy** [comment]
That's really weird.  Maybe I forgot to publish it.  Install it [from Git](https://github.com/transistorsoft/flutter_background_geolocation_firebase#or-latest-from-git) for now.

**Comment by christocracy** [comment]
Ok, [0.1.0](https://pub.dev/packages/background_geolocation_firebase/versions/0.1.0) is published.
